- name: Deploy Functions & Firestore
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > /tmp/sa.json
          npx firebase-tools deploy --only functions,firestore --project wifimap-852eb
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/sa.json
