name: Deploy to Firebase
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy
        run: firebase deploy --project wifimap-852eb --site wifimap-852eb --token "${{ secrets.FIREBASE_TOKEN }}" --only hosting
